xbtracer: cmake: protobuf: windows: suppress type conversion warning
The genereated protobuf cpp files with the compiler from XRT ext.new can
have warnning C4244 and C4267:

XRT-MCDM\build\WDebug\src\xrt\src\runtime_src\core\tools\xbtracer-new\func.pb.cc(748,15): error C2220: the following warning is treated as an error [XRT-MCDM\build\WDebug\src\xrt\src\runtime_src\core\tools\xbtracer-new\xbtracer_protobu
f.vcxproj]
XRT-MCDM\build\WDebug\src\xrt\src\runtime_src\core\tools\xbtracer-new\func.pb.cc(748,15): warning C4244: 'argument': conversion from 'uint64_t' to 'int', possible loss of data [XRT-MCDM\build\WDebug\src\xrt\src\runtime_src\core\tools\x
btracer-new\xbtracer_protobuf.vcxproj]
C:\Xilinx\XRT\ext.new\include\google\protobuf\has_bits.h(74,66): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data [XRT-MCDM\build\WDebug\src\xrt\src\runtime_src\core\tools\xbtracer-new\xbtracer_protobuf.vcxproj]
  (compiling source file 'func.pb.cc')
      C:\Xilinx\XRT\ext.new\include\google\protobuf\has_bits.h(74,66):
      the template instantiation context (the oldest one first) is
          C:\Xilinx\XRT\ext.new\include\google\protobuf\has_bits.h(84,25):
          see reference to class template instantiation 'google::protobuf::internal::HasBits<1>' being compiled
          C:\Xilinx\XRT\ext.new\include\google\protobuf\has_bits.h(73,8):
          while compiling class template member function 'void google::protobuf::internal::HasBits<1>::Or(const google::protobuf::internal::HasBits<1> &)'
              XRT-MCDM\build\WDebug\src\xrt\src\runtime_src\core\tools\xbtracer-new\func.pb.cc(391,23):
              see the first reference to 'google::protobuf::internal::HasBits<1>::Or' in 'xbtracer::Arg::_InternalParse'
And thus, we detect if MSVC is used suppress the above two warnings.

Signed-off-by: Wendy Liang <wendy.liang@amd.com>